extends: 
  - "standard"
  - "plugin:requirejs/recommended"
  - "plugin:jsdoc/recommended"
  - "plugin:compat/recommended"

parserOptions:
  ecmaVersion: 2015

env:
  es6: true
  browser: true
  amd: true
  jquery: true

plugins:
  - requirejs
  - deprecate
  - jsdoc

rules:
  "compat/compat": "warn"
  "indent": ["error", 4]
  "deprecate/function": "warn"
  "deprecate/member-expression": "warn"
  "deprecate/import": "warn"

settings:
  polyfills:
    - Promise
    - document.registerElement
    - ResizeObserver
    - fetch
    # core-js
    - Object.assign # es.object.assign
