env:
  es6: true
  browser: true
  amd: true

rules:
  block-spacing: ["error"]
  brace-style: ["error"]
  indent: ["error", 4, { "SwitchCase": 1 }]
  keyword-spacing: ["error"]
  max-statements-per-line: ["error"]
  no-empty: ["error"]
  no-extra-semi: ["error"]
  no-multiple-empty-lines: ["error", { "max": 1 }]
  no-trailing-spaces: ["error"]
  one-var: ["error", "never"]
  space-before-blocks: ["error"]
