trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  displayName: 'Install Node.js'
  inputs:
    versionSpec: '10.x'

- script: |
    yarn install
  displayName: 'Yarn Build'

- script: |
    yarn run lint
  displayName: 'Lint Javascript'

- script: |
    yarn pack
  displayName: 'Yarn Pack'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Package'
  inputs:
    PathtoPublish: '$(Build.SourcesDirectory)/jellyfin-web-v0.0.0.tgz'
    ArtifactName: 'jellyfin-web'
    publishLocation: 'Container'