trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    yarn install
  displayName: 'Yarn Build'
- task: CopyFiles@2
  inputs:
    Contents: |
      **
      !.editorconfig
      !.gitattributes
      !.gitignore
      !.git/**
      !.github/**
      !.drone.yml
      !.eslintrc.yml
      !.npmignore
      !run-eslint.sh
      !webpack.config.js
      !yarn.lock
      !node_modules/**
      !src/**
    TargetFolder: 'build'
    CleanTargetFolder: true
    OverWrite: true