trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  displayName: 'Install Node.js'
  inputs:
    versionSpec: '10.x'

- script: |
    yarn install
  displayName: 'Yarn Build'

- task: CopyFiles@2
  displayName: 'Copy Build Output'
  inputs:
    Contents: |
      **
      !.editorconfig
      !.gitattributes
      !.gitignore
      !.git/**
      !.github/**
      !.drone.yml
      !.eslintrc.yml
      !.npmignore
      !azure-pipelines.yml
      !run-eslint.sh
      !webpack.config.js
      !yarn.lock
      !node_modules/**
      !src/**
    TargetFolder: 'build'
    CleanTargetFolder: true
    OverWrite: true

- task: ArchiveFiles@2
  displayName: 'Create ZIP Package'
  inputs:
    rootFolderOrFile: '$(Build.BinariesDirectory)/build'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/jellyfin-web-$(Build.BuildId).zip'
    replaceExistingArchive: true