trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  displayName: 'Install Node.js'
  inputs:
    versionSpec: '10.x'

- script: |
    yarn install
  displayName: 'Yarn Build'

- script: |
    yarn pack
  displayName: 'Yarn Pack'

- task: ExtractFiles@1
  inputs:
    archiveFilePatterns: 'jellyfin-web-*.tgz'
    destinationFolder: 'package'
    cleanDestinationFolder: true

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(Build.BinariesDirectory)/package'
    includeRootFolder: true
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    replaceExistingArchive: true