trigger:
- master

jobs:
  - job: main_build
    displayName: 'Main Build'

    pool:
      vmImage: 'ubuntu-latest'

    steps:
    - task: NodeTool@0
      displayName: 'Install Node.js'
      inputs:
        versionSpec: '10.x'

    - script: |
        yarn install
      displayName: 'Install dependencies'

    - script: |
        yarn pack
      displayName: 'Build package'

    - task: PublishBuildArtifacts@1
      displayName: 'Publish package'
      inputs:
        PathtoPublish: '$(Build.SourcesDirectory)/jellyfin-web-v0.0.0.tgz'
        ArtifactName: 'jellyfin-web'
        publishLocation: 'Container'

  - job: lint
    displayName: 'Lint'

    pool:
      vmImage: 'ubuntu-latest'

    steps:
    - task: NodeTool@0
      displayName: 'Install Node.js'
      inputs:
        versionSpec: '10.x'

    - script: |
        yarn install
      displayName: 'Install dependencies'

    - script: |
        yarn run lint
      displayName: 'Run ESLint'
