variables:
  - name: WebVersion
  # This should match package.json version
  value: '0.0.0'

trigger:
- master

jobs:
  - job: main_build
    displayName: 'Main Build'

    pool:
      vmImage: 'ubuntu-latest'

    steps:
    - task: NodeTool@0
      displayName: 'Install Node.js'
      inputs:
        versionSpec: '10.x'

    - script: |
        yarn install
      displayName: 'Install dependencies'

    - script: |
        yarn pack
      displayName: 'Build package'

    - task: PublishPipelineArtifact@1
      displayName: 'Publish package'
      condition: succeeded()
      inputs:
        targetPath: '$(Build.SourcesDirectory)/jellyfin-web-v$(WebVersion).tgz'
        artifactName: 'jellyfin-web'

  - job: lint
    displayName: 'Lint'

    pool:
      vmImage: 'ubuntu-latest'

    steps:
    - task: NodeTool@0
      displayName: 'Install Node.js'
      inputs:
        versionSpec: '10.x'

    - script: |
        yarn install
      displayName: 'Install dependencies'

    - script: |
        yarn run lint
      displayName: 'Run ESLint'
