jobs:
- job: Lint
  displayName: 'Lint'

  pool:
    vmImage: 'ubuntu-latest'

  steps:
  - task: NodeTool@0
    displayName: 'Install Node'
    inputs:
      versionSpec: '12.x'

  - task: Cache@2
    displayName: 'Cache node_modules'
    inputs:
      key: 'yarn | yarn.lock'
      path: 'node_modules'

  - script: 'yarn install --frozen-lockfile'
    displayName: 'Install Dependencies'
    env:
      SKIP_PREPARE: 'true'

  - script: 'yarn run lint --quiet'
    displayName: 'Run ESLint'

  - script: 'yarn run stylelint'
    displayName: 'Run Stylelint'
